# Parameters used to generate this project with aem-project-archetype

groupId=com.rbc.aem.assets
artifactId=rbc-aem-assets
version=1.0.0-SNAPSHOT
package=com.rbc.aem.assets
appId=rbc-aem-assets
appTitle=RBC AEM Assets
aemVersion=cloud
sdkVersion=latest
languageCountry=${languageCountry}
includeExamples=n
includeErrorHandler=n
frontendModule=none
singleCountry=y
includeDispatcherConfig=y
includeCif=n
includeForms=n
includeFormsenrollment=n
includeFormscommunications=n
sdkFormsVersion=latest
commerceEndpoint=https://hostname.com/graphql
datalayer=n
amp=n
enableDynamicMedia=n
enableSSR=n
precompiledScripts=n
includeFormsheadless=n
